import { MD3LightTheme, MD3DarkTheme, configureFonts } from 'react-native-paper';

const fontConfig = {
  displayLarge: {
    fontFamily: 'Poppins-Bold',
    fontSize: 57,
    fontWeight: '700' as const,
    letterSpacing: 0,
    lineHeight: 64,
  },
  displayMedium: {
    fontFamily: 'Poppins-Bold',
    fontSize: 45,
    fontWeight: '700' as const,
    letterSpacing: 0,
    lineHeight: 52,
  },
  displaySmall: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 36,
    fontWeight: '600' as const,
    letterSpacing: 0,
    lineHeight: 44,
  },
  headlineLarge: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 32,
    fontWeight: '600' as const,
    letterSpacing: 0,
    lineHeight: 40,
  },
  headlineMedium: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 28,
    fontWeight: '600' as const,
    letterSpacing: 0,
    lineHeight: 36,
  },
  headlineSmall: {
    fontFamily: 'Poppins-Medium',
    fontSize: 24,
    fontWeight: '500' as const,
    letterSpacing: 0,
    lineHeight: 32,
  },
  titleLarge: {
    fontFamily: 'Poppins-Medium',
    fontSize: 22,
    fontWeight: '500' as const,
    letterSpacing: 0,
    lineHeight: 28,
  },
  titleMedium: {
    fontFamily: 'Inter-Medium',
    fontSize: 16,
    fontWeight: '500' as const,
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  titleSmall: {
    fontFamily: 'Inter-Medium',
    fontSize: 14,
    fontWeight: '500' as const,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  bodyLarge: {
    fontFamily: 'Inter-Regular',
    fontSize: 16,
    fontWeight: '400' as const,
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  bodyMedium: {
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    fontWeight: '400' as const,
    letterSpacing: 0.25,
    lineHeight: 20,
  },
  bodySmall: {
    fontFamily: 'Inter-Regular',
    fontSize: 12,
    fontWeight: '400' as const,
    letterSpacing: 0.4,
    lineHeight: 16,
  },
  labelLarge: {
    fontFamily: 'Inter-Medium',
    fontSize: 14,
    fontWeight: '500' as const,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelMedium: {
    fontFamily: 'Inter-Medium',
    fontSize: 12,
    fontWeight: '500' as const,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  labelSmall: {
    fontFamily: 'Inter-Medium',
    fontSize: 11,
    fontWeight: '500' as const,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
};

export const colors = {
  primary: '#2563eb',
  primaryContainer: '#dbeafe',
  secondary: '#059669',
  secondaryContainer: '#d1fae5',
  tertiary: '#ea580c',
  tertiaryContainer: '#fed7aa',
  surface: '#ffffff',
  surfaceContainer: '#f8fafc',
  surfaceContainerHighest: '#e2e8f0',
  background: '#ffffff',
  error: '#dc2626',
  errorContainer: '#fecaca',
  onPrimary: '#ffffff',
  onPrimaryContainer: '#1e40af',
  onSecondary: '#ffffff',
  onSecondaryContainer: '#047857',
  onTertiary: '#ffffff',
  onTertiaryContainer: '#c2410c',
  onSurface: '#0f172a',
  onSurfaceVariant: '#64748b',
  onBackground: '#0f172a',
  onError: '#ffffff',
  onErrorContainer: '#b91c1c',
  outline: '#94a3b8',
  outlineVariant: '#cbd5e1',
  shadow: '#000000',
  scrim: '#000000',
  inverseSurface: '#1e293b',
  inverseOnSurface: '#f1f5f9',
  inversePrimary: '#93c5fd',
  purple: '#7c3aed',
  purpleContainer: '#e0e7ff',
  gray: '#6b7280',
  grayContainer: '#f3f4f6',
};

export const darkColors = {
  ...colors,
  surface: '#0f172a',
  surfaceContainer: '#1e293b',
  surfaceContainerHighest: '#334155',
  background: '#020617',
  onSurface: '#f1f5f9',
  onSurfaceVariant: '#94a3b8',
  onBackground: '#f1f5f9',
  inverseSurface: '#f1f5f9',
  inverseOnSurface: '#1e293b',
};

export const theme = {
  ...MD3LightTheme,
  colors: colors,
  fonts: configureFonts({ config: fontConfig }),
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: darkColors,
  fonts: configureFonts({ config: fontConfig }),
};